test_suite_file = "test-run-execute.virter.toml"
test_timeout = "1m"
artifacts = [ "/etc/udev" ]

[[variants]]
# every variant needs a "name"
name = "postgres"
variables = {dbtype = "postgresql"}

[[variants]]
name = "maria"
variables = {dbtype = "mariadb"}
vm_tags = ["mariadb-server"]

[tests]
[tests.test_podman]
vms = [2]
vm_tags = ["podman"]

[tests.test_generic]
vms = [2]

[tests.extra_networks]
vms = [2]
[[tests.extra_networks.networks]]
forward = "nat"
dhcp = true
domain = "second-net"
