test_suite_file = "test-run-execute.virter.toml"
test_timeout = "1m"
artifacts = [ "/etc/udev" ]

[[variants]]
# every variant needs a "name"
name = "default"
variables = {dbtype = "mariadb"}

[tests]
[tests.example_test_a]
vms = [2]
tags = ["podman"]

[tests.example_test_b]
vms = [2]
tags = ["podman"]

[tests.extra_networks]
vms = [2]
tags = ["podman"]
[[tests.extra_networks.networks]]
forward = "nat"
dhcp = true
domain = "second-net"
