test_suite_file = "test-run-execute.virter.toml"
test_timeout = "1m"
artifacts = [ "/etc/udev" ]

[[variants]]
# every variant needs a "name"
name = "postgres"
variables.dbtype = "postgresql"

[[variants]]
name = "maria"
variables.dbtype = "mariadb"
vm_tags = ["mariadb-server"]

[[variants]]
name = "ipv6"
variables.dbtype = "mariadb"
ipv6 = true

[[networks]]
domain = "second-net"

[tests.test_podman]
vms = [2]
vm_tags = ["podman"]

[tests.test_generic]
vms = [2]

[tests.all_platforms]
vms = [2]
variants = ["postgres"]
needallplatforms = true

[tests.extra_networks]
vms = [2]
samevms = true
[[tests.extra_networks.networks]]
forward = "nat"
dhcp = true
domain = "third-net"
