name = "example"
provision_file = "test-run-provision.virter.toml"
provision_timeout = "40s"
provision_boot_capacity = "14G"

[[vms]]
vcpus = 2
memory = "6G"
boot_capacity = "20G"
base_image = "centos-7"
disks = ["name=data,size=5GiB"]
tags = ["podman"]
